### ISSUE TITLE
Can't flash OpenLog Qwiic

### ISSUE THREAD

**Issue by Stefal** [sparkfunX/Qwiic_OpenLog#4]
Hi!

My goal is to use OpenLog Qwiic as a standalone logger for the SparkFun GPS-RTK2 Board - ZED-F9P (Qwiic).

I've quick tested the OpenLog with an Arduino Uno and the OpenLog arduino library, and it's working.
My first step is simply updating the firmware with the latest one available here.
Then I will customize the code to log the F9P (any help is welcome).

But, I can't flash the OpenLog.

I've soldered the ftdi pins
Connected the OpenLog with an Adafruit Ftdi Friend/Sparkfun FTDI Basic 3.3v to a Windows Computer/Ubuntu Computer, and I always have the same problem : 
```
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0xde
```

I don't understand where is the problem.

**Comment by nseidle** [comment]
Just to be sure - did you get the Qwiic OpenLog from us? It's happened a few times where derivatives from other mfgs neglect/forget the bootloader.

The board should have a regular Uno/Optiboot bootloader preloaded onto the board. Be sure nothing else is connected to the board except your FTDI. Sounds like your already at 3.3V on the FTDI (good). Try loading the basic blink sketch onto OpenLog. The Stat pin is pin 13 so the default BLINK sketch should work.

**Comment by Stefal** [comment]
I bought it from [Digikey](https://www.digikey.fr/product-detail/en/sparkfun-electronics/DEV-15164/1568-DEV-15164-ND/9920435)

I can't flash the Blink sketch, I receive the same "not responding" error.

BTW : In all cases, when I start to upload the sketch, I see some activity on the FTDI adapter.

Thank you for your answer

**Comment by AndyEngland521** [comment]
@Stefal I've pulled an OpenLog and FTDI from stock and can't seem to reproduce your issue... I'd recommend maybe the [AVR Pocket Programmer](https://www.sparkfun.com/products/9825) to re-flash things, as this will neglect any lack of bootloader from a third party.
